/**
 * GENERATED by scripts/build-ribbon-profile.sh — do not edit by hand.
 * Re-run that script whenever public/meishi-ribbon.png changes.
 *
 * The line the photo is cut along: the ribbon's own upper outline, traced from
 * the artwork (1046×1738). Points run LEFT TO RIGHT across the whole card, `x` as
 * a fraction of the card width and `y` as a fraction of its height. Everything
 * ABOVE this line is photo; below it the ribbon takes over. Two points may
 * share an `x`: that is the line stepping up the shoulder of a tail.
 *
 * Traced from 1046 columns down to 14 points. The line runs
 * 2.0–6.5 rows below the ribbon's first opaque row, so the photo
 * always ends underneath the ribbon and never past the end of it.
 */
export const RIBBON_TOP: readonly (readonly [number, number])[] = [
  [0.000000, 0.488493],
  [0.053537, 0.488493],
  [0.053537, 0.490219],
  [0.127151, 0.490506],
  [0.127151, 0.474971],
  [0.176864, 0.473820],
  [0.176864, 0.455409],
  [0.822180, 0.454834],
  [0.822180, 0.473820],
  [0.873805, 0.474147],
  [0.873805, 0.489931],
  [0.947419, 0.489643],
  [0.947419, 0.487917],
  [1.000000, 0.487917],
] as const;
