/**
 * GENERATED by scripts/build-vector-art.sh — do not edit by hand.
 * Re-run that script whenever one of these files, or the picture it replaces,
 * changes.
 *
 * THE PARTS OF THE DESIGN THE PRINT FILE DRAWS AS LINE WORK.
 *
 * Everything the card places as a picture is a grid of pixels, and a printer's
 * proof enlarges that grid until the steps in it show along every edge. These
 * are the pieces that go in as the lines and shapes they were drawn as
 * instead — Illustrator exports carrying nothing but paths, with the caption's
 * lettering turned to outlines — so their edges are edges at any size.
 *
 * The screen preview goes on showing the pictures: nothing enlarges there, and
 * a `<img>` is what the browser is quickest with.
 *
 * WHERE EACH ONE GOES is measured, not assumed. The exports come off the
 * original artboard at the design's own size, but the pictures they replace
 * were exported at a size of their own and the card stretches them to fit —
 * for the ribbon that turns out to be ~1% — so the placement here is whatever
 * makes the line work land on the very pixels it replaces. `page` says where
 * the FILE'S OWN PAGE goes, as fractions of the card box (`x`/`width` of its
 * width, `y`/`height` of its height, `y` down from the top — the convention
 * lib/meishi-layout.ts states the whole layout in), so lib/print.ts places it
 * with the same `place()` it places everything else with. The numbers are
 * mostly outside 0…1 because the artboard is an A4 sheet and the card is a
 * small part of it: what lands on the card is the part of that sheet the
 * artwork is on.
 *
 * `fit` is how far the line work ended up from the picture it replaces, in
 * micrometres, measured edge by edge across the whole shape. The picture's own
 * grid is ~53 um, so these are inside the grain of the thing being matched.
 *
 * ribbon     1940 edges matched — rms 13.4 um, p99 50.5 um, worst 118.8 um (scale 1.00980 x 1.00697 vs the artboard)
 */

export type VectorArt = {
  /** The file: paths only, no pixels, no live text. */
  readonly url: string;
  /** The picture it replaces — still what the screen preview shows. */
  readonly raster: string;
  /**
   * The box to wipe to paper first, in card fractions: where the card's own
   * background picture carries this same part baked in. Nothing else of the
   * design is inside it.
   */
  readonly clear: {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  };
  /** Where the file's own page lands on the card, in card fractions. */
  readonly page: {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  };
  /** How far it lands from that picture: micrometres, over the whole shape. */
  readonly fit: {
    readonly rms: number;
    readonly p99: number;
    readonly worst: number;
  };
};

export const VECTOR_ART = {
  /** the ribbon and its anicas 所属タレント caption. */
  ribbon: {
    url: "/ribbon_only.pdf",
    raster: "/meishi-ribbon.png",
    clear: {
      x: 0.0516252,
      y: 0.4505178,
      width: 0.8977055,
      height: 0.1265823,
    },
    page: {
      x: -1.4273997,
      y: -1.1430017,
      width: 3.8555943,
      height: 3.2864799,
    },
    fit: { rms: 13.4, p99: 50.5, worst: 118.8 },
  },
} as const satisfies Record<string, VectorArt>;
